# Generated by Django 5.1.15 on 2026-05-28 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('fichas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Categoria de Prato',
                'verbose_name_plural': 'Categorias de Prato',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_atual', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
                ('motivo_indisponivel', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pratos', to='cardapio.categoriaprato')),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prato', to='fichas.fichatecnica')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preco_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_preco', to=settings.AUTH_USER_MODEL)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='cardapio.prato')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preço',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='prato',
            index=models.Index(condition=models.Q(('disponivel', True)), fields=['restaurante', 'categoria'], name='idx_prato_disponivel'),
        ),
    ]
