# Generated by Django 5.1.15 on 2026-05-28 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('aguardando_pedido', 'Aguardando Pedido'), ('em_atendimento', 'Em Atendimento'), ('aguardando_pagamento', 'Aguardando Pagamento')], default='livre', max_length=24)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('mesa', 'Mesa'), ('balcao', 'Balcão'), ('delivery', 'Delivery')], default='mesa', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('fiado', 'Fiado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.mesa')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_preparo', 'Em Preparo'), ('pronto', 'Pronto'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando', max_length=12)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('pronto_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='cardapio.prato')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Itens de Pedido',
            },
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(fields=('restaurante', 'numero'), name='uniq_mesa_numero_por_restaurante'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['restaurante', 'status'], name='idx_pedido_rest_status'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(condition=models.Q(('status__in', ['pago', 'cancelado']), _negated=True), fields=['mesa'], name='idx_pedido_mesa_aberto'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido', 'status'], name='idx_item_pedido_status'),
        ),
    ]
