# Generated by Django 5.1.15 on 2026-05-28 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('rendimento', models.PositiveIntegerField(default=1)),
                ('custo_total', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('custo_porcao', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
            },
        ),
        migrations.CreateModel(
            name='FichaIngrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidade', models.CharField(max_length=5)),
                ('principal', models.BooleanField(default=True)),
                ('custo_snapshot', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_fichas', to='estoque.ingrediente')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='fichas.fichatecnica')),
            ],
            options={
                'verbose_name': 'Ingrediente da Ficha',
                'verbose_name_plural': 'Ingredientes da Ficha',
            },
        ),
        migrations.CreateModel(
            name='FichaTecnicaVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versao', models.PositiveIntegerField()),
                ('dados', models.JSONField(default=dict)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='fichas.fichatecnica')),
            ],
            options={
                'verbose_name': 'Versão de Ficha Técnica',
                'verbose_name_plural': 'Versões de Ficha Técnica',
            },
        ),
    ]
