# Generated by Django 5.1.15 on 2026-05-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaingrediente',
            options={'verbose_name': 'Ingrediente da Receita', 'verbose_name_plural': 'Ingredientes da Receita'},
        ),
        migrations.AlterModelOptions(
            name='fichatecnica',
            options={'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterModelOptions(
            name='fichatecnicaversao',
            options={'verbose_name': 'Versão de Receita', 'verbose_name_plural': 'Versões de Receita'},
        ),
    ]
