# Generated by Django 5.1.15 on 2026-05-28 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Categoria de Ingrediente',
                'verbose_name_plural': 'Categorias de Ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('ativo', models.BooleanField(default=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('unidade_medida', models.CharField(choices=[('g', 'Grama'), ('kg', 'Quilograma'), ('ml', 'Mililitro'), ('L', 'Litro'), ('un', 'Unidade')], max_length=3)),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='estoque.categoriaingrediente')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('data_entrada', models.DateField()),
                ('nota_fiscal', models.CharField(blank=True, max_length=60)),
                ('validade', models.DateField(blank=True, null=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_estoque', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='estoque.fornecedor')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='estoque.ingrediente')),
            ],
            options={
                'verbose_name': 'Entrada de Estoque',
                'verbose_name_plural': 'Entradas de Estoque',
            },
        ),
        migrations.CreateModel(
            name='AjusteEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qtd_anterior', models.DecimalField(decimal_places=3, max_digits=12)),
                ('qtd_nova', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motivo', models.CharField(choices=[('inventario', 'Inventário'), ('avaria', 'Avaria'), ('vencimento', 'Vencimento'), ('roubo', 'Roubo'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.restaurante')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_estoque', to=settings.AUTH_USER_MODEL)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='estoque.ingrediente')),
            ],
            options={
                'verbose_name': 'Ajuste de Estoque',
                'verbose_name_plural': 'Ajustes de Estoque',
            },
        ),
        migrations.AddConstraint(
            model_name='categoriaingrediente',
            constraint=models.UniqueConstraint(fields=('restaurante', 'nome'), name='uniq_categoria_ingrediente_por_restaurante'),
        ),
        migrations.AddIndex(
            model_name='ingrediente',
            index=models.Index(condition=models.Q(('ativo', True)), fields=['restaurante'], name='idx_ingrediente_ativo'),
        ),
    ]
